import type { LayerId } from "@/components/layers";
import { Emblems } from "@/generators/emblems-generator";
import { Notes } from "@/generators/notes";

// Operations the Assistant may propose. Each is a public model-class method; see docs/prd/assistant.md

export interface Operation {
  run: (...args: any[]) => unknown;
  redraw: LayerId[];
}

const TERRITORY: LayerId[] = ["states", "borders", "provinces", "burgIcons", "labels", "military", "emblems"];

export const OPERATIONS: Record<string, Operation> = {
  "Burgs.rename": { run: (id, name) => Burgs.rename(id, name), redraw: ["labels"] },
  "Burgs.setPopulation": { run: (id, people) => Burgs.setPopulation(id, people), redraw: [] },
  "Burgs.setGroup": { run: (id, group) => Burgs.setGroup(id, group), redraw: ["burgIcons", "labels"] },
  "Burgs.setType": { run: (id, type) => Burgs.setType(id, type), redraw: [] },
  "Burgs.setBuilding": { run: (id, building, present) => Burgs.setBuilding(id, building, present), redraw: [] },
  "Burgs.setCulture": { run: (id, culture) => Burgs.setCulture(id, culture), redraw: [] },
  "Burgs.setPort": { run: (id, port) => Burgs.setPort(id, port), redraw: ["burgIcons"] },
  "Burgs.setCapital": { run: id => Burgs.setCapital(id), redraw: ["burgIcons", "labels"] },
  "Burgs.move": { run: (id, x, y) => Burgs.move(id, x, y), redraw: ["burgIcons", "labels", "emblems"] },
  "Burgs.add": { run: point => Burgs.add(point), redraw: ["burgIcons", "labels", "routes", "emblems"] },
  "Burgs.remove": { run: id => Burgs.remove(id), redraw: ["burgIcons", "labels", "emblems"] },
  "Burgs.setTreasury": { run: (id, amount) => Burgs.setTreasury(id, amount), redraw: [] },
  "Burgs.setLocked": { run: (id, locked) => Burgs.setLocked(id, locked), redraw: [] },
  "Burgs.setLink": { run: (id, url) => Burgs.setLink(id, url), redraw: [] },
  "States.rename": { run: (id, name) => States.rename(id, name), redraw: ["labels"] },
  "States.recolor": { run: (id, color) => States.recolor(id, color), redraw: ["states", "military"] },
  "States.setFullName": { run: (id, fullName) => States.setFullName(id, fullName), redraw: ["labels"] },
  "States.setForm": { run: (id, formName) => States.setForm(id, formName), redraw: ["labels"] },
  "States.setCulture": { run: (id, culture) => States.setCulture(id, culture), redraw: [] },
  "States.setType": { run: (id, type) => States.setType(id, type), redraw: [] },
  "States.setExpansionism": { run: (id, value) => States.setExpansionism(id, value), redraw: [] },
  "States.setRelation": { run: (id, other, relation) => States.setRelation(id, other, relation), redraw: [] },
  "States.recalculate": { run: () => States.recalculate(), redraw: [...TERRITORY, "goods"] },
  "States.merge": { run: (ruling, ids, asProvinces) => States.merge(ruling, ids, asProvinces), redraw: TERRITORY },
  "States.add": { run: (x, y) => States.add(x, y), redraw: [...TERRITORY, "routes"] },
  "States.remove": { run: id => States.remove(id), redraw: TERRITORY },
  "States.setTaxes": { run: (id, salesTax, pollTax) => States.setTaxes(id, salesTax, pollTax), redraw: [] },
  "States.setTreasury": { run: (id, amount) => States.setTreasury(id, amount), redraw: [] },
  "States.setLocked": { run: (id, locked) => States.setLocked(id, locked), redraw: [] },
  "States.setChronicleEntry": { run: (index, lines) => States.setChronicleEntry(index, lines), redraw: [] },
  "States.setCells": { run: (id, cells) => States.setCells(id, cells), redraw: TERRITORY },
  "Provinces.rename": { run: (id, name) => Provinces.rename(id, name), redraw: ["provinces", "labels"] },
  "Provinces.recolor": { run: (id, color) => Provinces.recolor(id, color), redraw: ["provinces"] },
  "Provinces.setFullName": { run: (id, fullName) => Provinces.setFullName(id, fullName), redraw: ["labels"] },
  "Provinces.setForm": { run: (id, formName) => Provinces.setForm(id, formName), redraw: ["labels"] },
  "Provinces.setCapital": { run: (id, burg) => Provinces.setCapital(id, burg), redraw: ["emblems"] },
  "Provinces.setState": { run: (id, state) => Provinces.setState(id, state), redraw: TERRITORY },
  "Provinces.add": { run: (x, y) => Provinces.add(x, y), redraw: ["provinces", "borders", "labels", "emblems"] },
  "Provinces.declareIndependence": { run: id => Provinces.declareIndependence(id), redraw: TERRITORY },
  "Provinces.remove": { run: id => Provinces.remove(id), redraw: ["provinces", "borders", "labels", "emblems"] },
  "Provinces.merge": {
    run: (primary, ids) => Provinces.merge(primary, ids),
    redraw: ["provinces", "borders", "labels", "emblems"]
  },
  "Provinces.setLocked": { run: (id, locked) => Provinces.setLocked(id, locked), redraw: [] },
  "Provinces.setCells": {
    run: (id, cells) => Provinces.setCells(id, cells),
    redraw: ["provinces", "borders", "labels"]
  },
  "Cultures.rename": { run: (id, name) => Cultures.rename(id, name), redraw: [] },
  "Cultures.recolor": { run: (id, color) => Cultures.recolor(id, color), redraw: ["cultures"] },
  "Cultures.setType": { run: (id, type) => Cultures.setType(id, type), redraw: [] },
  "Cultures.setBase": { run: (id, base) => Cultures.setBase(id, base), redraw: [] },
  "Cultures.setExpansionism": { run: (id, value) => Cultures.setExpansionism(id, value), redraw: [] },
  "Cultures.recalculate": { run: () => Cultures.recalculate(), redraw: ["cultures"] },
  "Cultures.add": { run: (x, y) => Cultures.add(x, y), redraw: ["cultures"] },
  "Cultures.remove": { run: id => Cultures.remove(id), redraw: ["cultures"] },
  "Cultures.setEmblemShape": { run: (id, shape) => Cultures.setEmblemShape(id, shape), redraw: ["emblems"] },
  "Cultures.setLocked": { run: (id, locked) => Cultures.setLocked(id, locked), redraw: [] },
  "Cultures.setOrigins": { run: (id, origins) => Cultures.setOrigins(id, origins), redraw: [] },
  "Cultures.setCode": { run: (id, code) => Cultures.setCode(id, code), redraw: [] },
  "Cultures.moveCenter": { run: (id, x, y) => Cultures.moveCenter(id, x, y), redraw: [] },
  "Cultures.setCells": { run: (id, cells) => Cultures.setCells(id, cells), redraw: ["cultures"] },
  "Religions.rename": { run: (id, name) => Religions.rename(id, name), redraw: [] },
  "Religions.recolor": { run: (id, color) => Religions.recolor(id, color), redraw: ["religions"] },
  "Religions.setDeity": { run: (id, deity) => Religions.setDeity(id, deity), redraw: [] },
  "Religions.setType": { run: (id, type) => Religions.setType(id, type), redraw: [] },
  "Religions.setForm": { run: (id, form) => Religions.setForm(id, form), redraw: [] },
  "Religions.setExpansion": { run: (id, expansion) => Religions.setExpansion(id, expansion), redraw: [] },
  "Religions.setExpansionism": { run: (id, value) => Religions.setExpansionism(id, value), redraw: [] },
  "Religions.recalculate": { run: () => Religions.recalculate(), redraw: ["religions"] },
  "Religions.add": { run: (x, y) => Religions.add(x, y), redraw: ["religions"] },
  "Religions.remove": { run: id => Religions.remove(id), redraw: ["religions"] },
  "Religions.setLocked": { run: (id, locked) => Religions.setLocked(id, locked), redraw: [] },
  "Religions.setOrigins": { run: (id, origins) => Religions.setOrigins(id, origins), redraw: [] },
  "Religions.setCode": { run: (id, code) => Religions.setCode(id, code), redraw: [] },
  "Religions.moveCenter": { run: (id, x, y) => Religions.moveCenter(id, x, y), redraw: [] },
  "Religions.setCells": { run: (id, cells) => Religions.setCells(id, cells), redraw: ["religions"] },
  "Biomes.rename": { run: (id, name) => Biomes.rename(id, name), redraw: [] },
  "Biomes.recolor": { run: (id, color) => Biomes.recolor(id, color), redraw: ["biomes"] },
  "Biomes.setHabitability": { run: (id, percent) => Biomes.setHabitability(id, percent), redraw: [] },
  "Biomes.add": { run: (name, color, habitability) => Biomes.add(name, color, habitability), redraw: [] },
  "Biomes.remove": { run: id => Biomes.remove(id), redraw: [] },
  "Rivers.rename": { run: (id, name) => Rivers.rename(id, name), redraw: ["labels"] },
  "Rivers.setType": { run: (id, type) => Rivers.setType(id, type), redraw: ["labels"] },
  "Rivers.add": { run: (x, y) => Rivers.add(x, y), redraw: ["rivers", "labels"] },
  "Rivers.remove": { run: id => Rivers.remove(id), redraw: ["rivers", "labels"] },
  "Rivers.setParent": { run: (id, parent) => Rivers.setParent(id, parent), redraw: [] },
  "Rivers.setWidth": {
    run: (id, sourceWidth, widthFactor) => Rivers.setWidth(id, sourceWidth, widthFactor),
    redraw: ["rivers"]
  },
  "Rivers.create": { run: cells => Rivers.create(cells), redraw: ["rivers", "labels"] },
  "Routes.rename": { run: (id, name) => Routes.rename(id, name), redraw: ["labels"] },
  "Routes.setGroup": { run: (id, group) => Routes.setGroup(id, group), redraw: ["routes", "labels"] },
  "Routes.add": { run: (from, to, group) => Routes.add(from, to, group), redraw: ["routes", "labels"] },
  "Routes.remove": { run: id => Routes.remove(id), redraw: ["routes", "labels"] },
  "Routes.setLocked": { run: (id, locked) => Routes.setLocked(id, locked), redraw: [] },
  "Routes.create": { run: (points, group) => Routes.create(points, group), redraw: ["routes", "labels"] },
  "Routes.split": { run: (id, pointIndex) => Routes.split(id, pointIndex), redraw: ["routes", "labels"] },
  "Routes.join": { run: (id, other) => Routes.join(id, other), redraw: ["routes", "labels"] },
  "Features.rename": { run: (id, name) => Features.rename(id, name), redraw: [] },
  "Features.setSubtype": { run: (id, subtype) => Features.setSubtype(id, subtype), redraw: [] },
  "Features.setGroup": { run: (id, group) => Features.setGroup(id, group), redraw: ["lakes"] },
  "Features.setCoastline": {
    run: (id, settings) => Features.setCoastline(id, settings),
    redraw: ["landmass", "coastline", "lakes"]
  },
  "Zones.rename": { run: (id, name) => Zones.rename(id, name), redraw: ["zones"] },
  "Zones.recolor": { run: (id, color) => Zones.recolor(id, color), redraw: ["zones"] },
  "Zones.setType": { run: (id, type) => Zones.setType(id, type), redraw: ["zones"] },
  "Zones.setHidden": { run: (id, hidden) => Zones.setHidden(id, hidden), redraw: ["zones"] },
  "Zones.setCells": { run: (id, cells) => Zones.setCells(id, cells), redraw: ["zones"] },
  "Zones.add": { run: (name, type, cells) => Zones.add(name, type, cells), redraw: ["zones"] },
  "Zones.remove": { run: id => Zones.remove(id), redraw: ["zones"] },
  "Markers.rename": { run: (id, name) => Markers.rename(id, name), redraw: [] },
  "Markers.setIcon": { run: (id, icon) => Markers.setIcon(id, icon), redraw: ["markers"] },
  "Markers.setType": { run: (id, type) => Markers.setType(id, type), redraw: ["markers"] },
  "Markers.setHidden": { run: (id, hidden) => Markers.setHidden(id, hidden), redraw: ["markers"] },
  "Markers.place": { run: (x, y, type, name, icon) => Markers.place(x, y, type, name, icon), redraw: ["markers"] },
  "Markers.remove": { run: id => Markers.remove(id), redraw: ["markers"] },
  "Markers.move": { run: (id, x, y) => Markers.move(id, x, y), redraw: ["markers"] },
  "Markers.setPinned": { run: (id, pinned) => Markers.setPinned(id, pinned), redraw: ["markers"] },
  "Markers.setLocked": { run: (id, locked) => Markers.setLocked(id, locked), redraw: [] },
  "Markers.setAppearance": { run: (id, appearance) => Markers.setAppearance(id, appearance), redraw: ["markers"] },
  "AddedLabels.rename": { run: (id, text) => AddedLabels.rename(id, text), redraw: ["labels"] },
  "AddedLabels.place": { run: (x, y, text, group) => AddedLabels.place(x, y, text, group), redraw: ["labels"] },
  "AddedLabels.remove": { run: id => AddedLabels.remove(id), redraw: ["labels"] },
  "Labels.setGroup": { run: (type, id, group) => Labels.setGroup(type, id, group), redraw: ["labels"] },
  "Labels.setLayout": { run: (type, id, layout) => Labels.setLayout(type, id, layout), redraw: ["labels"] },
  "Labels.reset": { run: (type, id) => Labels.reset(type, id), redraw: ["labels"] },
  "Military.rename": { run: (state, id, name) => Military.rename(state, id, name), redraw: ["military"] },
  "Military.remove": { run: (state, id) => Military.remove(state, id), redraw: ["military"] },
  "Military.add": { run: (state, x, y) => Military.add(state, x, y), redraw: ["military"] },
  "Military.setUnits": { run: (state, id, units) => Military.setUnits(state, id, units), redraw: ["military"] },
  "Military.setNaval": { run: (state, id, naval) => Military.setNaval(state, id, naval), redraw: ["military"] },
  "Military.setIcon": { run: (state, id, icon) => Military.setIcon(state, id, icon), redraw: ["military"] },
  "Military.move": { run: (state, id, x, y) => Military.move(state, id, x, y), redraw: ["military"] },
  "Military.rotate": { run: (state, id, angle) => Military.rotate(state, id, angle), redraw: ["military"] },
  "Military.setBase": { run: (state, id, x, y) => Military.setBase(state, id, x, y), redraw: ["military"] },
  "Military.split": { run: (state, id) => Military.split(state, id), redraw: ["military"] },
  "Military.attach": {
    run: (state, id, targetState, target) => Military.attach(state, id, targetState, target),
    redraw: ["military"]
  },
  "Emblems.set": { run: (key, coa) => Emblems.set(key, coa), redraw: ["emblems"] },
  "Emblems.regenerateOne": { run: key => Emblems.regenerateOne(key), redraw: ["emblems"] },
  "Emblems.place": { run: (key, x, y, size) => Emblems.place(key, x, y, size), redraw: ["emblems"] },
  "Journeys.add": { run: random => Journeys.add(random), redraw: ["journeys"] },
  "Journeys.remove": { run: id => Journeys.remove(id), redraw: ["journeys"] },
  "Journeys.rename": { run: (id, name) => Journeys.rename(id, name), redraw: [] },
  "Journeys.setType": { run: (id, type) => Journeys.setType(id, type), redraw: [] },
  "Journeys.recolor": { run: (id, color) => Journeys.recolor(id, color), redraw: ["journeys"] },
  "Journeys.setHidden": { run: (id, hidden) => Journeys.setHidden(id, hidden), redraw: ["journeys"] },
  "Journeys.setLocked": { run: (id, locked) => Journeys.setLocked(id, locked), redraw: [] },
  "Journeys.addSegment": { run: id => Journeys.addSegment(id), redraw: ["journeys"] },
  "Journeys.removeSegment": { run: (id, segment) => Journeys.removeSegment(id, segment), redraw: ["journeys"] },
  "Journeys.moveSegment": {
    run: (id, segment, index) => Journeys.moveSegment(id, segment, index),
    redraw: ["journeys"]
  },
  "Journeys.setSegment": {
    run: (id, segment, fields) => Journeys.setSegment(id, segment, fields),
    redraw: ["journeys"]
  },
  "Journeys.resetSegment": { run: (id, segment) => Journeys.resetSegment(id, segment), redraw: ["journeys"] },
  "Goods.rename": { run: (id, name) => Goods.rename(id, name), redraw: [] },
  "Goods.setIcon": { run: (id, icon) => Goods.setIcon(id, icon), redraw: ["goods"] },
  "Goods.recolor": { run: (id, color) => Goods.recolor(id, color), redraw: ["goods"] },
  "Goods.setPrice": { run: (id, value) => Goods.setPrice(id, value), redraw: [] },
  "Goods.setUnit": { run: (id, unit) => Goods.setUnit(id, unit), redraw: [] },
  "Goods.setTags": { run: (id, tags) => Goods.setTags(id, tags), redraw: [] },
  "Goods.setProduction": { run: (id, rules) => Goods.setProduction(id, rules), redraw: [] },
  "Markets.rename": { run: (id, name) => Markets.rename(id, name), redraw: ["markets"] },
  "Markets.recolor": { run: (id, color) => Markets.recolor(id, color), redraw: ["markets"] },
  "Notes.write": { run: (key, html) => Notes.write(key, html), redraw: [] }
};
