import type { LayerId } from "@/components/layers";
import { Emblems } from "@/generators/emblems-generator";
import { Lore } from "@/generators/lore";
import { Notes } from "@/generators/notes";

const TERRITORY: LayerId[] = ["states", "borders", "provinces", "burgIcons", "labels", "military", "emblems"];

// Operations the Assistant may propose, with the layers to redraw after them
export const OPERATIONS: Record<string, LayerId[]> = {
  "Burgs.rename": ["labels"],
  "Burgs.setPopulation": ["population"],
  "Burgs.setGroup": ["burgIcons", "labels"],
  "Burgs.setType": [],
  "Burgs.setBuilding": [],
  "Burgs.setCulture": [],
  "Burgs.setPort": ["burgIcons"],
  "Burgs.setCapital": ["burgIcons", "labels"],
  "Burgs.move": ["burgIcons", "labels", "emblems", "population"],
  "Burgs.add": ["burgIcons", "labels", "routes", "emblems", "population"],
  "Burgs.remove": ["burgIcons", "labels", "emblems", "population"],
  "Burgs.setTreasury": [],
  "Burgs.setLocked": [],
  "Burgs.setLink": [],
  "States.rename": ["labels"],
  "States.recolor": ["states", "military"],
  "States.setFullName": ["labels"],
  "States.setForm": ["labels"],
  "States.setCulture": [],
  "States.setType": [],
  "States.setExpansionism": [],
  "States.setRelation": [],
  "States.recalculate": [...TERRITORY, "goods"],
  "States.merge": TERRITORY,
  "States.add": [...TERRITORY, "routes"],
  "States.remove": TERRITORY,
  "States.setTaxes": [],
  "States.setTreasury": [],
  "States.setLocked": [],
  "States.setChronicleEntry": [],
  "States.setCells": TERRITORY,
  "States.setPopulation": ["population"],
  "Provinces.rename": ["provinces", "labels"],
  "Provinces.recolor": ["provinces"],
  "Provinces.setFullName": ["labels"],
  "Provinces.setForm": ["labels"],
  "Provinces.setCapital": ["emblems"],
  "Provinces.setState": TERRITORY,
  "Provinces.add": ["provinces", "borders", "labels", "emblems"],
  "Provinces.declareIndependence": TERRITORY,
  "Provinces.remove": ["provinces", "borders", "labels", "emblems"],
  "Provinces.merge": ["provinces", "borders", "labels", "emblems"],
  "Provinces.setPopulation": ["population"],
  "Provinces.setLocked": [],
  "Provinces.setCells": ["provinces", "borders", "labels", "emblems"],
  "Cultures.rename": [],
  "Cultures.recolor": ["cultures"],
  "Cultures.setType": [],
  "Cultures.setBase": [],
  "Cultures.setExpansionism": [],
  "Cultures.recalculate": ["cultures"],
  "Cultures.add": ["cultures"],
  "Cultures.remove": ["cultures"],
  "Cultures.setEmblemShape": ["emblems"],
  "Cultures.setLocked": [],
  "Cultures.setOrigins": [],
  "Cultures.setCode": [],
  "Cultures.moveCenter": [],
  "Cultures.setCells": ["cultures"],
  "Cultures.setPopulation": ["population"],
  "Religions.rename": [],
  "Religions.recolor": ["religions"],
  "Religions.setDeity": [],
  "Religions.setType": [],
  "Religions.setForm": [],
  "Religions.setExpansion": [],
  "Religions.setExpansionism": [],
  "Religions.recalculate": ["religions"],
  "Religions.add": ["religions"],
  "Religions.remove": ["religions"],
  "Religions.setLocked": [],
  "Religions.setOrigins": [],
  "Religions.setCode": [],
  "Religions.moveCenter": [],
  "Religions.setCells": ["religions"],
  "Religions.setPopulation": ["population"],
  "Biomes.rename": [],
  "Biomes.recolor": ["biomes"],
  "Biomes.setHabitability": [],
  "Biomes.add": [],
  "Biomes.remove": [],
  "Biomes.setCells": ["biomes"],
  "Biomes.restore": ["biomes"],
  "Rivers.rename": ["labels"],
  "Rivers.setType": ["labels"],
  "Rivers.add": ["rivers", "labels"],
  "Rivers.remove": ["rivers", "labels"],
  "Rivers.setParent": [],
  "Rivers.setWidth": ["rivers"],
  "Rivers.create": ["rivers", "labels"],
  "Routes.rename": ["labels"],
  "Routes.setGroup": ["routes", "labels"],
  "Routes.add": ["routes", "labels"],
  "Routes.remove": ["routes", "labels"],
  "Routes.setLocked": [],
  "Routes.create": ["routes", "labels"],
  "Routes.split": ["routes", "labels"],
  "Routes.join": ["routes", "labels"],
  "Features.rename": [],
  "Features.setSubtype": [],
  "Features.setGroup": ["lakes"],
  "Features.setCoastline": ["landmass", "coastline", "lakes"],
  "Zones.rename": ["zones"],
  "Zones.recolor": ["zones"],
  "Zones.setType": ["zones"],
  "Zones.setHidden": ["zones"],
  "Zones.setCells": ["zones"],
  "Zones.add": ["zones"],
  "Zones.remove": ["zones"],
  "Zones.setPopulation": ["population"],
  "Markers.rename": [],
  "Markers.setIcon": ["markers"],
  "Markers.setType": ["markers"],
  "Markers.setHidden": ["markers"],
  "Markers.place": ["markers"],
  "Markers.remove": ["markers"],
  "Markers.move": ["markers"],
  "Markers.setPinned": ["markers"],
  "Markers.setLocked": [],
  "Markers.setAppearance": ["markers"],
  "AddedLabels.rename": ["labels"],
  "AddedLabels.place": ["labels"],
  "AddedLabels.remove": ["labels"],
  "Labels.setGroup": ["labels"],
  "Labels.setLayout": ["labels"],
  "Labels.reset": ["labels"],
  "Military.rename": ["military"],
  "Military.remove": ["military"],
  "Military.add": ["military"],
  "Military.setAlert": ["military"],
  "Military.setUnits": ["military"],
  "Military.setNaval": ["military"],
  "Military.setIcon": ["military"],
  "Military.move": ["military"],
  "Military.rotate": ["military"],
  "Military.setBase": ["military"],
  "Military.split": ["military"],
  "Military.attach": ["military"],
  "Emblems.set": ["emblems"],
  "Emblems.regenerateOne": ["emblems"],
  "Emblems.place": ["emblems"],
  "Journeys.add": ["journeys"],
  "Journeys.remove": ["journeys"],
  "Journeys.rename": [],
  "Journeys.setType": [],
  "Journeys.recolor": ["journeys"],
  "Journeys.setHidden": ["journeys"],
  "Journeys.setLocked": [],
  "Journeys.addSegment": ["journeys"],
  "Journeys.removeSegment": ["journeys"],
  "Journeys.moveSegment": ["journeys"],
  "Journeys.setSegment": ["journeys"],
  "Journeys.resetSegment": ["journeys"],
  "Goods.rename": [],
  "Goods.setIcon": ["goods"],
  "Goods.recolor": ["goods"],
  "Goods.setPrice": [],
  "Goods.setUnit": [],
  "Goods.setTags": [],
  "Goods.setProduction": [],
  "Markets.rename": ["markets"],
  "Markets.recolor": ["markets"],
  "Lore.rename": [],
  "Lore.setYear": [],
  "Lore.setEra": [],
  "Lore.setDescription": [],
  "Notes.write": []
};

type Model = Record<string, (...args: unknown[]) => unknown>;

/** Run a registered operation; its model is a module or a generator singleton */
export function runOperation(op: string, args: unknown[]): unknown {
  const [name, method] = op.split(".");
  const model =
    ({ Emblems, Lore, Notes } as Record<string, unknown>)[name] ?? globalThis[name as keyof typeof globalThis];
  return (model as Model)[method](...args);
}
