// name generation approach and relative chance to be selected
const approach = {
  Number: 1,
  Being: 3,
  Adjective: 5,
  "Color + Animal": 5,
  "Adjective + Animal": 5,
  "Adjective + Being": 5,
  "Adjective + Genitive": 1,
  "Color + Being": 3,
  "Color + Genitive": 3,
  "Being + of + Genitive": 2,
  "Being + of the + Genitive": 1,
  "Animal + of + Genitive": 1,
  "Adjective + Being + of + Genitive": 2,
  "Adjective + Animal + of + Genitive": 2
};

// turn weighted data into a flat array
const approaches: string[] = Object.entries<number>(approach)
  .map(([approach, weight]) => new Array(weight).fill(approach))
  .flat();

const base = {
  number: ["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve"],
  being: [
    "Ancestor",
    "Ancient",
    "Brother",
    "Chief",
    "Council",
    "Creator",
    "Deity",
    "Elder",
    "Father",
    "Forebear",
    "Forefather",
    "Giver",
    "God",
    "Goddess",
    "Guardian",
    "Lady",
    "Lord",
    "Maker",
    "Master",
    "Mother",
    "Numen",
    "Overlord",
    "Reaper",
    "Ruler",
    "Sister",
    "Spirit",
    "Virgin"
  ],
  animal: [
    "Antelope",
    "Ape",
    "Badger",
    "Basilisk",
    "Bear",
    "Beaver",
    "Bison",
    "Boar",
    "Buffalo",
    "Camel",
    "Cat",
    "Centaur",
    "Chimera",
    "Cobra",
    "Crane",
    "Crocodile",
    "Crow",
    "Cyclope",
    "Deer",
    "Dog",
    "Dragon",
    "Eagle",
    "Elk",
    "Falcon",
    "Fox",
    "Goat",
    "Goose",
    "Hare",
    "Hawk",
    "Heron",
    "Horse",
    "Hound",
    "Hyena",
    "Ibis",
    "Jackal",
    "Jaguar",
    "Kraken",
    "Lark",
    "Leopard",
    "Lion",
    "Mantis",
    "Marten",
    "Moose",
    "Mule",
    "Narwhal",
    "Owl",
    "Ox",
    "Panther",
    "Pegasus",
    "Phoenix",
    "Rat",
    "Raven",
    "Rook",
    "Scorpion",
    "Serpent",
    "Shark",
    "Sheep",
    "Snake",
    "Sphinx",
    "Spider",
    "Swan",
    "Tiger",
    "Turtle",
    "Unicorn",
    "Viper",
    "Vulture",
    "Walrus",
    "Wolf",
    "Wolverine",
    "Worm",
    "Wyvern"
  ],
  adjective: [
    "Aggressive",
    "Almighty",
    "Ancient",
    "Beautiful",
    "Benevolent",
    "Big",
    "Blind",
    "Blond",
    "Bloody",
    "Brave",
    "Broken",
    "Brutal",
    "Burning",
    "Calm",
    "Cheerful",
    "Crazy",
    "Cruel",
    "Dead",
    "Deadly",
    "Devastating",
    "Distant",
    "Disturbing",
    "Divine",
    "Dying",
    "Eternal",
    "Evil",
    "Explicit",
    "Fair",
    "Far",
    "Fat",
    "Fatal",
    "Favorable",
    "Flying",
    "Friendly",
    "Frozen",
    "Giant",
    "Good",
    "Grateful",
    "Great",
    "Happy",
    "High",
    "Holy",
    "Honest",
    "Huge",
    "Hungry",
    "Immutable",
    "Infallible",
    "Inherent",
    "Last",
    "Latter",
    "Lost",
    "Loud",
    "Lucky",
    "Mad",
    "Magical",
    "Main",
    "Major",
    "Marine",
    "Naval",
    "New",
    "Old",
    "Patient",
    "Peaceful",
    "Pregnant",
    "Prime",
    "Proud",
    "Pure",
    "Sacred",
    "Sad",
    "Scary",
    "Secret",
    "Selected",
    "Severe",
    "Silent",
    "Sleeping",
    "Slumbering",
    "Strong",
    "Sunny",
    "Superior",
    "Sustainable",
    "Troubled",
    "Unhappy",
    "Unknown",
    "Waking",
    "Wild",
    "Wise",
    "Worried",
    "Young"
  ],
  genitive: [
    "Cold",
    "Day",
    "Death",
    "Doom",
    "Fate",
    "Fire",
    "Fog",
    "Frost",
    "Gates",
    "Heaven",
    "Home",
    "Ice",
    "Justice",
    "Life",
    "Light",
    "Lightning",
    "Love",
    "Nature",
    "Night",
    "Pain",
    "Snow",
    "Springs",
    "Summer",
    "Thunder",
    "Time",
    "Victory",
    "War",
    "Winter"
  ],
  theGenitive: [
    "Abyss",
    "Blood",
    "Dawn",
    "Earth",
    "East",
    "Eclipse",
    "Fall",
    "Harvest",
    "Moon",
    "North",
    "Peak",
    "Rainbow",
    "Sea",
    "Sky",
    "South",
    "Stars",
    "Storm",
    "Sun",
    "Tree",
    "Underworld",
    "West",
    "Wild",
    "Word",
    "World"
  ],
  color: [
    "Amber",
    "Black",
    "Blue",
    "Bright",
    "Brown",
    "Dark",
    "Golden",
    "Green",
    "Grey",
    "Light",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "White",
    "Yellow"
  ]
};

const forms = {
  Folk: {Shamanism: 2, Animism: 2, "Ancestor worship": 1, Polytheism: 2},
  Organized: {Polytheism: 5, Dualism: 1, Monotheism: 4, "Non-theism": 1},
  Cult: {Cult: 1, "Dark Cult": 1},
  Heresy: {Heresy: 1}
};

const methods = {
  "Random + type": 3,
  "Random + ism": 1,
  "Supreme + ism": 5,
  "Faith of + Supreme": 5,
  "Place + ism": 1,
  "Culture + ism": 2,
  "Place + ian + type": 6,
  "Culture + type": 4
};

export const types = {
  Shamanism: {Beliefs: 3, Shamanism: 2, Spirits: 1},
  Animism: {Spirits: 1, Beliefs: 1},
  "Ancestor worship": {Beliefs: 1, Forefathers: 2, Ancestors: 2},
  Polytheism: {Deities: 3, Faith: 1, Gods: 1, Pantheon: 1},

  Dualism: {Religion: 3, Faith: 1, Cult: 1},
  Monotheism: {Religion: 1, Church: 1},
  "Non-theism": {Beliefs: 3, Spirits: 1},

  Cult: {Cult: 4, Sect: 4, Arcanum: 1, Coterie: 1, Order: 1, Worship: 1},
  "Dark Cult": {Cult: 2, Sect: 2, Blasphemy: 1, Circle: 1, Coven: 1, Idols: 1, Occultism: 1},

  Heresy: {
    Heresy: 3,
    Sect: 2,
    Apostates: 1,
    Brotherhood: 1,
    Circle: 1,
    Dissent: 1,
    Dissenters: 1,
    Iconoclasm: 1,
    Schism: 1,
    Society: 1
  }
};

export const religionsData = {approaches, base, forms, methods, types};
