import { createTypedArray, getTypedArray, last, TYPED_ARRAY_MAX, unique } from "./arrayUtils";
import { C_12, getColors, getMixedColor, getRandomColor, toHEX } from "./colorUtils";
import {
  clipPoly,
  debounce,
  generateDate,
  getBase64,
  getCoordinates,
  getLatitude,
  getLongitude,
  getSegmentId,
  isCtrlClick,
  link,
  openURL,
  parseError,
  speak,
  throttle,
  wiki
} from "./commonUtils";
import { drawCellsValue, drawPath, drawPoint, drawPolygons, drawRouteConnections } from "./debugUtils";
import { downloadFile, getFileName, uploadFile } from "./fileUtils";
import { distanceSquared, rollups } from "./functionUtils";
import {
  calculateVoronoi,
  drawHeights,
  findAllCellsInRadius,
  findAllInQuadtree,
  findClosestCell,
  findGridAll,
  findGridCell,
  generateGrid,
  getGridPolygon,
  getPackPolygon,
  isLand,
  isWater,
  poissonDiscSampler,
  shouldRegenerateGrid
} from "./graphUtils";
import { abbreviate, getAdjective, isVowel, list, nth, trimVowels } from "./languageUtils";
import { applyOption, ensureEl, findEl, getComposedPath, getNextId, getPointer } from "./nodeUtils";
import { lerp, lim, minmax, normalize, rn } from "./numberUtils";
import { connectVertices, findPath, getIsolines, getPolesOfInaccessibility, getVertexPath } from "./pathUtils";
import { biased, each, gauss, generateSeed, getNumberInRange, P, Pint, ra, rand, rw } from "./probabilityUtils";
import { capitalize, isValidJSON, parseTransform, round, safeParseJSON, sanitizeId, splitInTwo } from "./stringUtils";
import {
  convertTemperature,
  formatPrice,
  getArea,
  getAreaUnit,
  getCellPopulation,
  getFriendlyHeight,
  getFriendlyPrecipitation,
  getHeight,
  getIntegerFromSI,
  getPrecipitation,
  getTemperatureLikeness,
  si
} from "./unitUtils";

declare global {
  interface JSON {
    isValid: (str: string) => boolean;
    safeParse: (str: string) => any;
  }
}

export {
  abbreviate,
  applyOption,
  biased,
  C_12,
  calculateVoronoi,
  capitalize,
  clipPoly,
  connectVertices,
  convertTemperature,
  createTypedArray,
  debounce,
  distanceSquared,
  downloadFile,
  drawCellsValue,
  drawHeights,
  drawPath,
  drawPoint,
  drawPolygons,
  drawRouteConnections,
  each,
  ensureEl,
  findAllCellsInRadius,
  findAllInQuadtree,
  findClosestCell,
  findEl,
  findGridAll,
  findGridCell,
  findPath,
  formatPrice,
  gauss,
  generateDate,
  generateGrid,
  generateSeed,
  getAdjective,
  getArea,
  getAreaUnit,
  getBase64,
  getCellPopulation,
  getColors,
  getComposedPath,
  getCoordinates,
  getFileName,
  getFriendlyHeight,
  getFriendlyPrecipitation,
  getGridPolygon,
  getHeight,
  getIntegerFromSI,
  getIsolines,
  getLatitude,
  getLongitude,
  getMixedColor,
  getNextId,
  getNumberInRange,
  getPackPolygon,
  getPointer,
  getPolesOfInaccessibility,
  getPrecipitation,
  getRandomColor,
  getSegmentId,
  getTemperatureLikeness,
  getTypedArray,
  getVertexPath,
  isCtrlClick,
  isLand,
  isValidJSON,
  isVowel,
  isWater,
  last,
  lerp,
  lim,
  link,
  list,
  minmax,
  normalize,
  nth,
  openURL,
  P,
  Pint,
  parseError,
  parseTransform,
  poissonDiscSampler,
  ra,
  rand,
  rn,
  rollups,
  round,
  rw,
  safeParseJSON,
  sanitizeId,
  shouldRegenerateGrid,
  si,
  speak,
  splitInTwo,
  TYPED_ARRAY_MAX,
  throttle,
  toHEX,
  trimVowels,
  unique,
  uploadFile,
  wiki
};
