import { chargeData } from "./chargeData";

export const charges = {
  types: {
    conventional: 33, // 40 charges
    crosses: 13, // 30 charges
    beasts: 7, // 41 charges
    beastHeads: 3, // 10 charges
    birds: 3, // 16 charges
    reptiles: 2, // 5 charges
    bugs: 2, // 8 charges
    fishes: 1, // 3 charges
    molluscs: 1, // 2 charges
    plants: 3, // 18 charges
    fantastic: 5, // 14 charges
    agriculture: 2, // 8 charges
    arms: 5, // 32 charges
    bodyparts: 2, // 12 charges
    people: 2, // 4 charges
    architecture: 3, // 11 charges
    seafaring: 3, // 9 charges
    tools: 3, // 15 charges
    miscellaneous: 5, // 30 charges
    inescutcheon: 3, // 43 charges
    ornaments: 0, // 9 charges
    uploaded: 0,
  },
  single: {
    conventional: 10,
    crosses: 8,
    beasts: 7,
    beastHeads: 3,
    birds: 3,
    reptiles: 2,
    bugs: 2,
    fishes: 1,
    molluscs: 1,
    plants: 3,
    fantastic: 5,
    agriculture: 2,
    arms: 5,
    bodyparts: 2,
    people: 2,
    architecture: 3,
    seafaring: 3,
    tools: 3,
    miscellaneous: 5,
    inescutcheon: 1,
  },
  semy: {
    conventional: 4,
    crosses: 1,
  },
  conventional: {
    annulet: 4,
    billet: 5,
    carreau: 1,
    comet: 1,
    compassRose: 1,
    crescent: 5,
    delf: 0,
    estoile: 1,
    fleurDeLis: 6,
    fountain: 1,
    fusil: 4,
    gear: 1,
    goutte: 4,
    heart: 4,
    lozenge: 2,
    lozengeFaceted: 3,
    lozengePloye: 1,
    mascle: 4,
    moonInCrescent: 1,
    mullet: 5,
    mullet10: 1,
    mullet4: 3,
    mullet6: 4,
    mullet6Faceted: 1,
    mullet6Pierced: 1,
    mullet7: 1,
    mullet8: 1,
    mulletFaceted: 1,
    mulletPierced: 1,
    pique: 2,
    roundel: 4,
    roundel2: 3,
    rustre: 2,
    spiral: 1,
    sun: 3,
    sunInSplendour: 1,
    sunInSplendour2: 1,
    trefle: 2,
    triangle: 3,
    trianglePierced: 1,
  },
  crosses: {
    crossHummetty: 15,
    crossVoided: 1,
    crossPattee: 2,
    crossPatteeAlisee: 1,
    crossFormee: 1,
    crossFormee2: 2,
    crossPotent: 2,
    crossJerusalem: 1,
    crosslet: 1,
    crossClechy: 3,
    crossBottony: 1,
    crossFleury: 3,
    crossPatonce: 1,
    crossPommy: 1,
    crossGamma: 1,
    crossArrowed: 1,
    crossFitchy: 1,
    crossCercelee: 1,
    crossMoline: 2,
    crossFourchy: 1,
    crossAvellane: 1,
    crossErminee: 1,
    crossBiparted: 1,
    crossMaltese: 3,
    crossTemplar: 2,
    crossCeltic: 1,
    crossCeltic2: 1,
    crossTriquetra: 1,
    crossCarolingian: 1,
    crossOccitan: 1,
    crossSaltire: 3,
    crossBurgundy: 1,
    crossLatin: 3,
    crossPatriarchal: 1,
    crossOrthodox: 1,
    crossCalvary: 1,
    crossDouble: 1,
    crossTau: 1,
    crossSantiago: 1,
    crossAnkh: 1,
  },
  beasts: {
    agnusDei: 1,
    badgerStatant: 1,
    bearPassant: 1,
    bearRampant: 3,
    boarRampant: 1,
    bullPassant: 1,
    camel: 1,
    catPassantGuardant: 1,
    cowStatant: 1,
    dolphin: 1,
    elephant: 1,
    goat: 1,
    greyhoundCourant: 1,
    greyhoundRampant: 1,
    greyhoundSejant: 1,
    hedgehog: 1,
    hindStatant: 1,
    horsePassant: 1,
    horseRampant: 2,
    horseSalient: 1,
    lamb: 1,
    lambPassantReguardant: 1,
    lionPassant: 3,
    lionPassantGuardant: 2,
    lionRampant: 7,
    lionSejant: 2,
    martenCourant: 1,
    mastiffStatant: 1,
    porcupine: 1,
    rabbitSejant: 1,
    ramPassant: 1,
    ratRampant: 1,
    rhinoceros: 1,
    squirrel: 1,
    stagLodgedRegardant: 1,
    stagPassant: 1,
    talbotPassant: 1,
    talbotSejant: 1,
    wolfPassant: 1,
    wolfRampant: 1,
    wolfStatant: 1,
  },
  beastHeads: {
    boarHeadErased: 1,
    bullHeadCaboshed: 1,
    deerHeadCaboshed: 1,
    donkeyHeadCaboshed: 1,
    elephantHeadErased: 1,
    horseHeadCouped: 1,
    lionHeadCaboshed: 2,
    lionHeadErased: 2,
    ramHeadErased: 1,
    wolfHeadErased: 2,
  },
  birds: {
    cock: 3,
    dove: 2,
    doveDisplayed: 1,
    duck: 1,
    eagle: 9,
    falcon: 2,
    heron: 1,
    owl: 1,
    owlDisplayed: 1,
    parrot: 1,
    peacock: 1,
    peacockInPride: 1,
    raven: 2,
    swallow: 1,
    swan: 2,
    swanErased: 1,
  },
  reptiles: {
    crocodile: 1,
    frog: 1,
    lizard: 1,
    ouroboros: 1,
    snake: 1,
  },
  bugs: {
    bee: 1,
    butterfly: 1,
    cancer: 1,
    dragonfly: 1,
    fly: 1,
    ladybird: 1,
    scorpion: 1,
    wasp: 1,
  },
  fishes: {
    pike: 1,
    plaice: 1,
    salmon: 1,
  },
  molluscs: {
    escallop: 4,
    snail: 1,
  },
  plants: {
    apple: 1,
    cinquefoil: 1,
    earOfWheat: 1,
    grapeBunch: 1,
    grapeBunch2: 1,
    mapleLeaf: 1,
    oak: 1,
    palmTree: 1,
    pear: 1,
    pineCone: 1,
    pineTree: 1,
    quatrefoil: 1,
    rose: 1,
    sextifoil: 1,
    thistle: 1,
    tree: 1,
    trefoil: 1,
    wheatStalk: 1,
  },
  fantastic: {
    angel: 3,
    basilisk: 1,
    centaur: 1,
    dragonPassant: 3,
    dragonRampant: 2,
    eagleTwoHeads: 2,
    griffinPassant: 1,
    griffinRampant: 2,
    pegasus: 1,
    sagittarius: 1,
    serpent: 1,
    unicornRampant: 1,
    wyvern: 1,
    wyvernWithWingsDisplayed: 1,
  },
  agriculture: {
    garb: 2,
    millstone: 1,
    plough: 1,
    ploughshare: 1,
    rake: 1,
    scythe: 1,
    scythe2: 1,
    sickle: 1,
  },
  arms: {
    arbalest: 1,
    arbalest2: 1,
    arrow: 1,
    arrowsSheaf: 1,
    axe: 3,
    bow: 1,
    bowWithArrow: 2,
    bowWithThreeArrows: 1,
    cannon: 1,
    falchion: 1,
    flamberge: 1,
    flangedMace: 1,
    gauntlet: 1,
    grenade: 1,
    hatchet: 3,
    helmet: 2,
    helmetCorinthian: 1,
    helmetGreat: 2,
    helmetZischagge: 1,
    lanceHead: 1,
    lanceWithBanner: 1,
    lochaberAxe: 1,
    mace: 1,
    maces: 1,
    mallet: 1,
    rapier: 1,
    sabre: 1,
    sabre2: 1,
    sabresCrossed: 1,
    shield: 1,
    spear: 1,
    sword: 4,
  },
  bodyparts: {
    armEmbowedHoldingSabre: 1,
    armEmbowedVambraced: 1,
    armEmbowedVambracedHoldingSword: 1,
    bone: 1,
    crossedBones: 2,
    foot: 1,
    hand: 4,
    head: 1,
    headWreathed: 1,
    skeleton: 2,
    skull: 2,
    skull2: 1,
  },
  people: {
    archer: 1,
    cavalier: 3,
    cossack: 1,
    monk: 1,
  },
  architecture: {
    bridge: 1,
    bridge2: 1,
    castle: 2,
    castle2: 1,
    column: 1,
    lighthouse: 1,
    palace: 1,
    pillar: 1,
    portcullis: 1,
    tower: 2,
    windmill: 1,
  },
  seafaring: {
    anchor: 6,
    armillarySphere: 1,
    boat: 2,
    boat2: 1,
    caravel: 1,
    drakkar: 1,
    lymphad: 2,
    raft: 1,
    shipWheel: 1,
  },
  tools: {
    anvil: 2,
    drawingCompass: 2,
    fan: 1,
    hook: 1,
    ladder: 1,
    ladder2: 1,
    pincers: 1,
    saw: 1,
    scale: 1,
    scaleImbalanced: 1,
    scalesHanging: 1,
    scissors: 1,
    scissors2: 1,
    shears: 1,
    trowel: 1,
  },
  miscellaneous: {
    attire: 2,
    banner: 2,
    bell: 3,
    bookClosed: 1,
    bookClosed2: 1,
    bookOpen: 1,
    bucket: 1,
    buckle: 1,
    bugleHorn: 2,
    bugleHorn2: 1,
    chain: 2,
    chalice: 2,
    cowHorns: 3,
    crosier: 1,
    crown: 3,
    crown2: 2,
    drum: 1,
    fasces: 1,
    feather: 3,
    harp: 2,
    horseshoe: 3,
    hourglass: 2,
    key: 3,
    laurelWreath: 2,
    laurelWreath2: 1,
    log: 1,
    lute: 2,
    lyre: 1,
    mitre: 1,
    orb: 1,
    pot: 2,
    ramsHorn: 1,
    sceptre: 1,
    scrollClosed: 1,
    snowflake: 1,
    stagsAttires: 1,
    stirrup: 2,
    wheel: 3,
    wing: 2,
    wingSword: 1,
  },
  inescutcheon: {
    inescutcheonHeater: 1,
    inescutcheonSpanish: 1,
    inescutcheonFrench: 1,
    inescutcheonHorsehead: 1,
    inescutcheonHorsehead2: 1,
    inescutcheonPolish: 1,
    inescutcheonHessen: 1,
    inescutcheonSwiss: 1,
    inescutcheonBoeotian: 1,
    inescutcheonRoman: 1,
    inescutcheonKite: 1,
    inescutcheonOldFrench: 1,
    inescutcheonRenaissance: 1,
    inescutcheonBaroque: 1,
    inescutcheonTarge: 1,
    inescutcheonTarge2: 1,
    inescutcheonPavise: 1,
    inescutcheonWedged: 1,
    inescutcheonFlag: 1,
    inescutcheonPennon: 1,
    inescutcheonGuidon: 1,
    inescutcheonBanner: 1,
    inescutcheonDovetail: 1,
    inescutcheonGonfalon: 1,
    inescutcheonPennant: 1,
    inescutcheonRound: 1,
    inescutcheonOval: 1,
    inescutcheonVesicaPiscis: 1,
    inescutcheonSquare: 1,
    inescutcheonDiamond: 1,
    inescutcheonNo: 1,
    inescutcheonFantasy1: 1,
    inescutcheonFantasy2: 1,
    inescutcheonFantasy3: 1,
    inescutcheonFantasy4: 1,
    inescutcheonFantasy5: 1,
    inescutcheonNoldor: 1,
    inescutcheonGondor: 1,
    inescutcheonEasterling: 1,
    inescutcheonErebor: 1,
    inescutcheonIronHills: 1,
    inescutcheonUrukHai: 1,
    inescutcheonMoriaOrc: 1,
  },
  ornaments: {
    mantle: 0,
    ribbon1: 3,
    ribbon2: 2,
    ribbon3: 1,
    ribbon4: 1,
    ribbon5: 1,
    ribbon6: 1,
    ribbon7: 1,
    ribbon8: 1,
  },
  data: chargeData,
};
