// Style form labels the schema leaves to the key ("stroke-width" → "Stroke width") and its group captions,
// in the interface language. A test keeps every schema key listed
import { t } from "@/utils/i18n";

export const KEY_LABELS: Record<string, string> = {
  anchors: t("Anchors"),
  attrs: t("Attrs"),
  back: t("Back"),
  bands: t("Bands"),
  barSize: t("Bar size"),
  base: t("Base"),
  biomes: t("Biomes"),
  borders: t("Borders"),
  bottom: t("Bottom"),
  box: t("Box"),
  boxSize: t("Box size"),
  burgEmblems: t("Burg emblems"),
  burgIcons: t("Burg icons"),
  cells: t("Cells"),
  circle: t("Circle"),
  coastline: t("Coastline"),
  color: t("Color"),
  columns: t("Columns"),
  compass: t("Compass"),
  compassRose: t("Compass rose"),
  contours: t("Contours"),
  coordinates: t("Coordinates"),
  count: t("Count"),
  cultures: t("Cultures"),
  curve: t("Curve"),
  density: t("Density"),
  dx: "Dx",
  dy: "Dy",
  embellishment: t("Embellishment"),
  emblems: t("Emblems"),
  fill: t("Fill"),
  "fill-opacity": t("Fill opacity"),
  filter: t("Filter"),
  fogging: t("Fogging"),
  "font-family": t("Font family"),
  "font-size": t("Font size"),
  "font-style": t("Font style"),
  "font-weight": t("Font weight"),
  goods: t("Goods"),
  goodsBurgs: t("Goods burgs"),
  goodsCells: t("Goods cells"),
  goodsIcons: t("Goods icons"),
  grid: t("Grid"),
  groups: t("Groups"),
  hachures: t("Hachures"),
  halo: t("Halo"),
  height: t("Height"),
  heightmap: t("Heightmap"),
  href: t("Href"),
  ice: t("Ice"),
  icon: t("Icon"),
  iconSize: t("Icon size"),
  icons: t("Icons"),
  interval: t("Interval"),
  journeys: t("Journeys"),
  label: t("Label"),
  labels: t("Labels"),
  lake_island: t("Lake island"),
  lakes: t("Lakes"),
  landHeights: t("Land heights"),
  landmass: t("Landmass"),
  left: t("Left"),
  legend: t("Legend"),
  length: t("Length"),
  "letter-spacing": t("Letter spacing"),
  map: t("Map"),
  markers: t("Markers"),
  markets: t("Markets"),
  mask: t("Mask"),
  military: t("Military"),
  mode: t("Mode"),
  ocean: t("Ocean"),
  oceanHeights: t("Ocean heights"),
  oceanLayers: t("Ocean layers"),
  oceanWaves: t("Ocean waves"),
  opacity: t("Opacity"),
  options: t("Options"),
  outline: t("Outline"),
  pattern: t("Pattern"),
  population: t("Population"),
  precipitation: t("Precipitation"),
  provinceBorders: t("Province borders"),
  provinceEmblems: t("Province emblems"),
  provinces: t("Provinces"),
  reach: t("Reach"),
  relax: t("Relax"),
  relief: t("Relief"),
  religions: t("Religions"),
  render: t("Render"),
  right: t("Right"),
  rivers: t("Rivers"),
  routes: t("Routes"),
  rulers: t("Rulers"),
  rural: t("Rural"),
  rx: "Rx",
  ry: "Ry",
  scale: t("Scale"),
  scaleBar: t("Scale Bar"),
  scheme: t("Scheme"),
  sea_island: t("Sea island"),
  set: t("Set"),
  shade: t("Shade"),
  shore: t("Shore"),
  size: t("Size"),
  skip: t("Skip"),
  spacing: t("Spacing"),
  stateBorders: t("State borders"),
  stateEmblems: t("State emblems"),
  states: t("States"),
  statesBody: t("States body"),
  statesHalo: t("States halo"),
  stroke: t("Stroke"),
  "stroke-dasharray": t("Stroke dasharray"),
  "stroke-linecap": t("Stroke linecap"),
  "stroke-linejoin": t("Stroke linejoin"),
  "stroke-opacity": t("Stroke opacity"),
  "stroke-width": t("Stroke width"),
  style: t("Style"),
  temperature: t("Temperature"),
  terracing: t("Terracing"),
  texture: t("Texture"),
  top: t("Top"),
  trade: t("Trade"),
  transform: t("Transform"),
  type: t("Type"),
  urban: t("Urban"),
  vignette: t("Vignette"),
  width: t("Width"),
  x: "X",
  y: "Y",
  zones: t("Zones")
};

export const GROUP_LABELS: Record<string, string> = {
  Fill: t("Fill"),
  Font: t("Font"),
  Label: t("Label"),
  Outline: t("Outline"),
  Padding: t("Padding"),
  Position: t("Position"),
  Stroke: t("Stroke")
};
